### ISSUE TITLE
[QUESTION] - Access to Cellular or SMS texts from Windows?

### ISSUE THREAD

**Issue by Espionage724** [WoA-OnePlus-6-Series/WoA-on-OnePlus6-Series#2]
### Question

I'm wondering if there's a way to view SMS texts and/or do voice calls over cellular while running Windows on OP6? Last I tried with W10 LTE data worked. I have VoLTE and VoWiFi on Android (stock OOS and LineageOS 21).

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Not possible
